package com.csse.transport.controller;

import com.csse.transport.model.BusFare;
import com.csse.transport.repository.BusFareRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller  // This means that this class is a Controller
@RequestMapping(path="/sl-trans") // This means URL's start with /demo (after Application path)
public class BusFareController {

    @Autowired   // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private BusFareRepository busFareRepository;

    @GetMapping(path="/add") //Map only get requests
    public @ResponseBody String addNewFare (@RequestParam String username, @RequestParam String password){

        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        BusFare bf = new BusFare();
        bf.setBusFareID(BusfareID);
        bf.setBusStopID(busStopID);
        bf.setRouteID(routeID);
        bf.setHalt_1ID(halt1ID);
        bf.setHalt_2ID(halt2ID);
        bf.setHalt1Latitude(halt1Latitude);
        bf.setHalt1Longitude(halt1Longitude);
        bf.setHalt2Latitude(halt2Latitude);
        bf.setHalt2Longitude(halt2Longitude);
        bf.setDistanceBetweenHalts(distance);



        busFareRepository.save(bf);
        return "Bus fare added to database successfully";
    }

    @GetMapping(path="/all-fares")
    public @ResponseBody Iterable<BusFare> getAllBusFares(){
        //This returns a JSON or XML with the users
        return busFareRepository.findAll();
    }
}


//testing
//http://localhost:8080/sl-trans/add?username=nadun&password=112233
//http://localhost:8080/sl-trans/all-users