package com.csse.transport.controller;

import com.csse.transport.model.BusStop;
import com.csse.transport.repository.BusStopRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller  // This means that this class is a Controller
@RequestMapping(path="/sl-trans") // This means URL's start with /demo (after Application path)
public class BusStopController {

    @Autowired   // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private BusStopRepository busstopRepository;

    @GetMapping(path="/addroute") //Map only get requests
    public @ResponseBody String addNewBusStop (@RequestParam String routeID){

        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request


        BusStop bs = new BusStop();
        bs.setBusHaltID(sID);
        bs.setRouteID(routeID);
        bs.setTownID(tID);
        bs.setBusHaltName(busName);
        bs.setBusHaltLatitude(BusLatitude);
        bs.setBusHaltLongitude(BusLongitude);
        busstopRepository.save(bs);
        return "Bus stop Added Successfully";

    }

    @GetMapping(path="/all-stops")
    public @ResponseBody Iterable<BusStop> getAllBusStops(){
        //This returns a JSON or XML with the users
        return busstopRepository.findAll();
    }
}


//testing
//http://localhost:8080/sl-trans/add?username=nadun&password=112233
//http://localhost:8080/sl-trans/all-users