package com.csse.transport.controller;

import com.csse.transport.model.Route;
import com.csse.transport.repository.RouteRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

//@Controller  // This means that this class is a Controller
//@RequestMapping(path="/sl-trans") // This means URL's start with /demo (after Application path)
public class RouteController {

//    @Autowired   // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private RouteRepository routeRepository;

//    @GetMapping(path="/addroute") //Map only get requests
//    public @ResponseBody String addNewRoute (@RequestParam String routeID){

        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

//        ///making an object and calling the setters to set values to attribute feilds in data base
//        Route r = new Route();
//        r.setRouteID(routeID);
//        r.setOrigin(sID);
//        r.setOriginLatitude(originLatitude);
//        r.setOriginLongitude(originLongitude);
//        r.setDestination(dID);
//        r.setDesLatitude(DesLatitude);
//        r.setDesLongitude(DesLongitude);
//        routeRepository.save(r);
//        return "Route Added Successfully";

//    }

//    @GetMapping(path="/all-routes")
//    public @ResponseBody Iterable<Route> getAllRoutes(){
//        //This returns a JSON or XML with the users
//        return routeRepository.findAll();
//    }
}


//testing
//http://localhost:8080/sl-trans/add?username=nadun&password=112233
//http://localhost:8080/sl-trans/all-users