package com.csse.transport.controller;

import com.csse.transport.model.User;
import com.csse.transport.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller  // This means that this class is a Controller
@RequestMapping(path="/sl-trans") // This means URL's start with /sl-trans (after Application path)
public class UserController {

    @Autowired   // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @GetMapping(path="/add") //Map only get requests
    public @ResponseBody String addNewUser (@RequestParam String username, @RequestParam String password){

        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        User n = new User();
        n.setUsername(username);
        n.setPassword(password);
        userRepository.save(n);
        return "User Registered successfully";
    }

    @GetMapping(path="/all-users")
    public @ResponseBody Iterable<User> getAllUsers(){
        //This returns a JSON or XML with the users
        return userRepository.findAll();
    }
}


//testing
//http://localhost:8080/sl-trans/add?username=nadun&password=112233
//http://localhost:8080/sl-trans/all-users